class PyNUTError(Exception): ...

class PyNUTClient:
    def __init__(
        self,
        host: str = "127.0.0.1",
        port: int = 3493,
        login=None,
        password=None,
        debug: bool = False,
        timeout: int = 5,
    ) -> None: ...
    def __del__(self) -> None: ...
    def GetUPSList(self): ...
    def GetUPSNames(self): ...
    def GetUPSVars(self, ups: str = ""): ...
    def CheckUPSAvailable(self, ups: str = ""): ...
    def GetUPSCommands(self, ups: str = ""): ...
    def GetRWVars(self, ups: str = ""): ...
    def SetRWVar(self, ups: str = "", var: str = "", value: str = ""): ...
    def RunUPSCommand(self, ups: str = "", command: str = ""): ...
    def DeviceLogin(self, ups: str = ""): ...
    def FSD(self, ups: str = ""): ...
    def help(self): ...
    def ver(self): ...
    def ListClients(self, ups=None): ...
